### ISSUE TITLE
Add support for plugin dependencies

### ISSUE THREAD

**Issue by ben-manes** [mikepenz/gradle-dependency-submission#101]
This is a neat project. I noticed that you might have forgotten about `buildEnvironment` to capture updates on the plugin classpath.

```
Help tasks
----------
buildEnvironment - Displays all buildscript dependencies declared in root project 'caffeine'.
dependencies - Displays all dependencies declared in root project 'caffeine'.
```

**Comment by mikepenz** [comment]
@ben-manes that's a great idea / addition. If possible I will have a look at that in the upcoming days.

**Comment by mikepenz** [comment]
So I had a look into it, but I am not yet sure on how to best add it. 

What variant would you say makes most sense:
- execute the `buildEnvironment` for every module and have the resolved tree merged with the specific manifest
- execute the `buildEnvironment` for every module and have the resolved tree uploaded as its own standalone manifest (with a different name in some form)
- execute only for the root module and have it merged with other dependencies if requested
- execute only for root module and have as its own manifest
- offer ability to configure for which modules to execute it (and have it merged? or standalone manifest?)

**Comment by ben-manes** [comment]
I think all of the plugins are on the root project's classpath, even if only applied at a subproject. Since its the classpath it must commingle as a single execution environment. Therefore I'd lean towards _"execute only for root module and have as its own manifest"_.
