### ISSUE TITLE
Ability to specify the package for dependents

### ISSUE THREAD

**Issue by ben-manes** [mikepenz/gradle-dependency-submission#102]
For Maven, Github can calculate the `Dependents` on the `Dependency graph` (e.g. [Guava's](https://github.com/google/guava/network/dependents?package_id=UGFja2FnZS0xNzk4OTA4NTM%3D)). It would be neat to let Gradle projects have a similar analysis which is otherwise empty (e.g. [Caffeine's](https://github.com/ben-manes/caffeine/network/dependents)).

**Comment by mikepenz** [comment]
@ben-manes as far as I am aware, the dependents is something GitHub does automatically for some projects (I have not been able to identify by which pattern this happens, for example `okhttp` has dependents) 

At least the documentation also does not seem to mention `dependents`: https://docs.github.com/en/rest/dependency-graph/dependency-submission

I did ask about that as part of: https://github.com/community/community/discussions/19492 but there was no proper answer given yet :/

**Comment by ben-manes** [comment]
Thanks, if it's not possible yet then lets close this.

**Comment by mikepenz** [comment]
@ben-manes possibly the library has to be deployed to the `github` maven repo 🤔 for it to identify the package. 
this behaviour doesn't seem to be documented anywhere though. especially as it also seems to result in false mappings. for example if you look at:
<img width="992" alt="Screenshot 2022-09-03 at 20 22 29" src="https://user-images.githubusercontent.com/1476232/188283475-0da8e5eb-0b06-4278-be6b-7551521ac561.png">

linking to a repo which is for sure not the official one. Even more interesting it lists dependents which is also completely off:
https://github.com/Aheadboy/kotlinx-coroutines/network/dependents

--- 

As far as I can tell - the action will build the full snapshot the API currently accepts.
