### ISSUE TITLE
Fails to parse entries with '\--- ' instead of '\\--- '

### ISSUE THREAD

**Issue by stergios-t** [mikepenz/gradle-dependency-submission#202]
When running `./gradlew --console plain :bob:dependencies --configuration runtimeClasspath` using Gradle 7.6 , its output is like:
![image](https://user-images.githubusercontent.com/62663392/215103613-2a1692f1-1f25-416a-838f-db8423b4702d.png)

Yet DEPENDENCY_DEPENDENCY_LEVEL_END in
https://github.com/mikepenz/gradle-dependency-submission/blob/bb8f9fd31df790ee7ccbb681d4b0330829305a4f/src/parse.ts#L4-L9
makes the action to expect an output like:
![image](https://user-images.githubusercontent.com/62663392/215103962-3fad7cdb-5053-4847-82f8-ed849a7c49d1.png)

I assume because previous versions of Gradle have been outputting '\\\\--- ' and not '\\--- '
This causes the parser to ignore/omit dependencies of that output that _only_ exist in entries with '\\--- ' and not also with '+--- '

**Comment by mikepenz** [comment]
Thank you very much for the report @stergios-t will give it a look

**Comment by mikepenz** [comment]
So this is actually correct: `'\\--- '` with the first `\` escaping the second `\`. 

Verified this by running the tests with 7.5.1 and 7.6 resulting in the same. 

Could you please provide more details on what is failing for you?

**Comment by stergios-t** [comment]
Hmm, this looks to be more complicated that I initially thought.
Yes, you're correct, this does not look be related to the parsing of '\\\\--- ' vs '\\--- ' (definitely not an expert in js/ts! :D )

Here is the original issue: 
Trying to gather the dependencies of a gradle project that has 3 subprojects bob, bob-api and bob-mock, where bob-api is a dependency of both bob and bob-mock.
There is one root project build.gradle that has the configuration for all subprjoects

When setting up the action with
![image](https://user-images.githubusercontent.com/62663392/215140518-3712a464-673e-407f-aed1-f73125ab6d31.png)

it generates manifests for bob and bob-api but nothing for bob-mock
Also in each manifest Many dependencies are missing comparing to the gradle dependencies output

When setting the action with (just an order swap)
![image](https://user-images.githubusercontent.com/62663392/215143568-845450e6-1268-478c-9726-8805b4d2c07b.png)

it again generates manifests for bob and bob-api but nothing for bob-mock but this time the manifects have all the dependencies in place, comparing to the gradle dependencies output..

(subsequent multiple tests lead me down the wrong path of '\\\\--- ' vs '\\--- ' )

The main questions are:
- Is the order and/or interdependency of the subprojects relate to the missing dependencies in the manifest?
- What could cause not to generate the manifest for bob-mock, even though `./gradlew --console plain :bob-mock:dependencies --configuration runtimeClasspath` generates a complete output just like bob and bob-api ?
- Am I doing maybe something wrong in the setup of the action?

**Comment by mikepenz** [comment]
Thank you for providing additional details. Based on all the screenshots, things generally look all good. 

We had run the action on much larger and much more complex projects (with many more modules) and it worked - so there must be something different about that module. 

Is the given project open source for me to have a look at? or would it be possible to reproduce this in a simpler way, allowing to debug further?

**Comment by stergios-t** [comment]
Hi @mikepenz , thanks for taking the time looking into this.
Ok got it, so this behavior is more related to the specific configuration of the gradle tool in the project and its subprojects
Hi @mikepenz , thanks for taking the time looking into this.
Ok got it, so this behavior is more related to the specific configuration of the gradle tool in the project and its subprojects

Unfortunately its not open source and can't do much about sharing any code or logs, but thanks for offering to help out a js/ts noob like me! 🙇 

Either way, getting the dependencies of just one subproject is good enough for the current needs (which actually works as expected), so there's no reason to spend more of your effort.
Unfortunately its not open source and can't do much about sharing any code or logs, but thanks for offering to help out a js/ts noob like me! 🙇 

Either way, getting the dependencies of just one subproject is good enough for the current needs (which actually works as expected), so there's no reason to spend more of your effort.
