### ISSUE TITLE
Failed to extract gradle version

### ISSUE THREAD

**Issue by TnoAlex** [mikepenz/gradle-dependency-submission#212]
![image](https://user-images.githubusercontent.com/72296772/218656077-02a4e6ad-c5b2-4b33-88b7-88fea89ce856.png)
And my gradle version is 7.6

**Comment by mikepenz** [comment]
What does the output for `./gradlew --version` or `gradle --version` look like for you?

**Comment by TnoAlex** [comment]
It looks like this
![image](https://user-images.githubusercontent.com/72296772/218675131-8a79dd0f-961d-47a1-afe6-3d231bccd343.png)

**Comment by mikepenz** [comment]
oh you require to call the `*.bat` file. 

The action was mainly tested and developed on Unix based systems. So it looks there are some windows related issues. 

 
 E.g. the action either uses `gradle` or `gradlew` but not `gradlew.bat`:
 - https://github.com/mikepenz/gradle-dependency-submission/blob/main/src/gradle.ts#L192
 
 This will be something to look into, I currently don't have a windows based system at hand, so it may not be as simple for me to test this

**Comment by TnoAlex** [comment]
When I use Ubuntu, I get the following error
![image](https://user-images.githubusercontent.com/72296772/218703138-733da610-7144-4fba-b9ac-07955b7202fd.png)
But I'm sure gradlew exists, and here are the results of my run in my local wsl
![image](https://user-images.githubusercontent.com/72296772/218703527-168180cc-5244-4829-90a9-edc47f1c8a44.png)

**Comment by mikepenz** [comment]
did you get the above output using `./gradlew` on ubuntu? (the version output)? 

Please make sure the file is executable too, and that it exists at the exact location as the error indicates.

**Comment by TnoAlex** [comment]
Thank you very much, when I added the setting to give Gradlew permission to run in the GitHub workflow, it has run successfully👍
