### ISSUE TITLE
Dependency parsing doesn't cope with substitutions or platform BOM versions.

### ISSUE THREAD

**Issue by quotidian-ennui** [mikepenz/gradle-dependency-submission#230]
I'll try my best to describe the setup; I may even be able to update this with a link to a project eventually.

Gradle Wrapper Version = 7.5.1

## Project A, the upstream dependency

I'm not in control of this, so there's not an awful lot I can do about Project A

```
implementation("org.eclipse.jetty.aggregate:jetty-all:9.4.49.v20220914")
implementation("org.bouncycastle:bcprov-jdk15on:1.70")
implementation("org.bouncycastle:bcpkix-jdk15on:1.70")
implementation("org.bouncycastle:bcmail-jdk15on:1.70")
```

## Project B, something that depends on Project A

This is what we're in control of.

- We know that jdk15on variants of bcprov have been "discontinued and will never have any updates" because they regard it as badly named so they introduced an jdk18on.
- We know we can use the `platform()` feature to upgrade jetty...

```
resolutionStrategy.dependencySubstitution {
    // Redirect bouncy castle jdk15on to jdk18on
    substitute module('org.bouncycastle:bcprov-jdk15on') using module("org.bouncycastle:bcprov-jdk18on:1.72")
    substitute module('org.bouncycastle:bcprov-ext-jdk15on') using module("org.bouncycastle:bcprov-ext-jdk18on:1.72")
    substitute module('org.bouncycastle:bcpkix-jdk15on') using module("org.bouncycastle:bcpkix-jdk18on:1.72")
    substitute module('org.bouncycastle:bcmail-jdk15on') using module("org.bouncycastle:bcmail-jdk18on:1.72")
    substitute module('org.bouncycastle:bcutil-jdk15on') using module("org.bouncycastle:bcutil-jdk18on:1.72")
    substitute module('org.bouncycastle:bcpg-jdk15on') using module("org.bouncycastle:bcpg-jdk18on:1.72")
    substitute module('org.bouncycastle:bcjmail-jdk15on') using module("org.bouncycastle:bcjmail-jdk18on:1.72")
    substitute module('org.bouncycastle:bctls-jdk15on') using module("org.bouncycastle:bctls-jdk18on:1.72")
}
... other bits and bobs of gradle

implementation (platform("org.eclipse.jetty:jetty-bom:9.4.51.v20230217"))
implementation ("org.bouncycastle:bcprov-jdk18on:1.72")
implementation ("org.bouncycastle:bcpkix-jdk18on:1.72")
implementation ("org.bouncycastle:bcmail-jdk18on:1.72")
```

## Running gradle dependencies

It effectively gives us this in a `gradle --console plain dependencies > deps.txt`

```
|    +--- com.adaptris:interlok-common:4.7.0-RELEASE
... 
|    |    \--- org.eclipse.jetty.aggregate:jetty-all:9.4.49.v20220914
|    |         +--- org.eclipse.jetty:jetty-client:9.4.49.v20220914 -> 9.4.51.v20230217
|    |         |    +--- org.eclipse.jetty:jetty-http:9.4.51.v20230217

... more jetty- things skipped like jetty-io/jetty-webapp etc.
|    |         +--- org.eclipse.jetty:jetty-util:9.4.49.v20220914 -> 9.4.51.v20230217
|    |         +--- org.eclipse.jetty:jetty-jaspi:9.4.49.v20220914 -> 9.4.51.v20230217
|    +--- org.bouncycastle:bcprov-jdk15on:1.70 -> org.bouncycastle:bcprov-jdk18on:1.72
|    +--- org.bouncycastle:bcpkix-jdk15on:1.70 -> org.bouncycastle:bcpkix-jdk18on:1.72
|    |    +--- org.bouncycastle:bcprov-jdk18on:1.72
|    |    \--- org.bouncycastle:bcutil-jdk18on:1.72
|    |         \--- org.bouncycastle:bcprov-jdk18on:1.72
|    +--- org.bouncycastle:bcmail-jdk15on:1.70 -> org.bouncycastle:bcmail-jdk18on:1.72
|    |    +--- org.bouncycastle:bcprov-jdk18on:1.72
|    |    +--- org.bouncycastle:bcutil-jdk18on:1.72 (*)
|    |    \--- org.bouncycastle:bcpkix-jdk18on:1.72 (*)

... Other stuff skipped for brevity.

+--- org.bouncycastle:bcprov-jdk18on:1.72
+--- org.bouncycastle:bcpkix-jdk18on:1.72 (*)
+--- org.bouncycastle:bcmail-jdk18on:1.72 (*)
+--- org.eclipse.jetty:jetty-bom:9.4.51.v20230217
|    +--- org.eclipse.jetty:jetty-client:9.4.51.v20230217 (c)
|    +--- org.eclipse.jetty:jetty-deploy:9.4.51.v20230217 (c)
|    +--- org.eclipse.jetty:jetty-jmx:9.4.51.v20230217 (c)
|    +--- org.eclipse.jetty:jetty-plus:9.4.51.v20230217 (c)
|    +--- org.eclipse.jetty:jetty-annotations:9.4.51.v20230217 (c)
|    +--- org.eclipse.jetty:jetty-util:9.4.51.v20230217 (c)
...
```

## The end result via submission API

What ultimately happens is that

- 9.4.49 is reported as the version for everything that's jetty related, even though everything has been optimistically upgraded to 9.4.51; 
  - a cursory glance at parseGradlePackage suggests that it should do the the right thing so it's probably my misunderstanding about the levels and such.
- org.bouncycastle:bcmail-jdk15on is reported as version `org.bouncycastle`
- org.bouncycastle:bcmail-jdk18on is reported as version `1.72`
- org.bouncycastle:bcpkix-jdk15on is reported as version `org.bouncycastle`
- org.bouncycastle:bcpkix-jdk18on is reported as version `1.72`
- org.bouncycastle:bcprov-jdk15on is reported as version `org.bouncycastle`
- org.bouncycastle:bcprov-jdk18on is reported as version `1.72`

- Dependabot has raised a bunch of alerts on bcprov-jdk15on which have to be dismissed.

It seems to me that it's the `parse.ts#parseGradlePackage` method that is doing not parsing the line properly for the substitutions.

I can't explain the situation with 9.4.51 vs 9.4.49 for jetty. There are no references to 9.4.51 anywhere in the dependency

**Comment by jcopenhop** [comment]
I'm having this problem with bouncycastle and a custom `resolutionStrategy` as well. I believe the issue is in https://github.com/mikepenz/gradle-dependency-submission/blob/main/src/parse.ts#L28. It is doesn't handle the case of `org.bouncycastle:bcprov-jdk15on:[1.62,2) -> org.bouncycastle:bcprov-jdk18on:1.76` which will end up with 4 parts. This gets parsed as:

```
        PackageURL {
          type: 'maven',
          name: 'bcprov-jdk15on',
          namespace: 'org.bouncycastle',
          version: 'org.bouncycastle',
          qualifiers: null,
          subpath: null
        }
```

**Comment by mikepenz** [comment]
I know this is an old issue, however the provided `deps.txt` does look to resolve in the right results with the latest version. 

@jcopenhop would you please be so kind to provide a `deps.txt` output for your scenario?

**Comment by jcopenhop** [comment]
@mikepenz Sorry. It is a private project and the deps are quite large. Here is a redacted output with just the deps that include `bouncycastle`. They should show the problem as I tested it in the https://github.com/mikepenz/gradle-dependency-submission/blob/main/__tests__/parse.test.ts by adding the `+-- org.bouncycastle:bcprov-jdk15on:[1.62,2) -> org.bouncycastle:bcprov-jdk18on:1.76` line to one of the tests and showing the resulting `PackageURL`

[deps.txt](https://github.com/mikepenz/gradle-dependency-submission/files/13055614/deps.txt)

**Comment by mikepenz** [comment]
Thank you for providing the details. Unfortunately, there is no more plan to work on this, with the official gradle build action having support now for the dependency submission API. 

Really appreciate the help!

Please head over to this project for more details: https://github.com/gradle/gradle-build-action?tab=readme-ov-file#github-dependency-graph-support
