### ISSUE TITLE
subprojects in subdirectories not supported

### ISSUE THREAD

**Issue by danielstravito** [mikepenz/gradle-dependency-submission#237]
Consider this directory structure:

```
/build.gradle.kts
/app/api2/build.gradlel.kts
/app/api/build.gradle.kts
/app/api-extra/build.gradle.kts
/libraries/lib1/build.gradle.kts
/libraries/lib2/build.gradle.kts
```

And this dependency graph for `:app:api`:
```
                 ┌────────────┐
                 │  :app:api  ├────┐
                 └─────┬──────┘    │
                       │           │
                       │           │
     ┌─────────────────┴┐      ┌───┴─────────────┐
     │  :app:api-extra  │      │ :libraries:lib1 │
     └──────────────────┘      └────────┬────────┘
                                        │
                               ┌────────┴────────┐
                               │ :libraries:lib2 │
                               └─────────────────┘
```

This will fail with something like this:

```
FAILURE: Build failed with an exception.

* What went wrong:
Cannot locate tasks that match 'app-extra:dependencies' as project 'app-extra' not found in root project 'myproject'.

* Try:
> Run gradlew projects to get a list of available projects.
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
```

A workaround would be to list each and every subproject, and ignore subprojects, like:

```
      - name: Run snapshot action
        uses: mikepenz/gradle-dependency-submission@v0.8.5
        with:
          gradle-build-module: |-
            :app:api
            :app:api2
            :app:api-extra
            :libraries:lib1
            :libraries:lib2
          sub-module-mode: 'IGNORE'
```

But if these five subprojects all depend on a 3rd party library with a vulnerability, then the vulnerability view in GitHub would contain 5 duplicate entries, or in a bigger project, 150 entries. 

Speculation: It also seems like the script doesn't track already resolved dependencies, so if all of those targets depend on a shared 3rd party dependency, this script seems to lookup details about that dependency 5 times, which is very time consuming as 5 grows to a large number. Just a guess why it takes such an extreme amount of time to execute with explicit build modules.

**Comment by mikepenz** [comment]
Can you please provide a test project to reproduce this?

**Comment by mikepenz** [comment]
There is no more plan to work on this, with the official gradle build action having support now for the dependency submission API. 

Please head over to this project for more details: https://github.com/gradle/gradle-build-action?tab=readme-ov-file#github-dependency-graph-support
