### ISSUE TITLE
Build fails on lower JDK versions

### ISSUE THREAD

**Issue by ejektaflex** [mikepenz/gradle-dependency-submission#249]
I received the following error:
```md
Error: 
  FAILURE: Build failed with an exception.
  
  * Where:
  Build file '/home/runner/work/Bountiful/Bountiful/build.gradle.kts' line: 53
  
  * What went wrong:
  Failed to apply plugin 'dev.architectury.loom'.
  > You are using an outdated version of Java (11). Java 17 or higher is required.
    The JAVA_HOME environment variable is currently set to (/usr/lib/jvm/temurin-11-jdk-amd64).
  
  * Try:
  > Run with --stacktrace option to get the stack trace.
  > Run with --info or --debug option to get more log output.
  > Run with --scan to get full insights.
  
  * Get more help at https://help.gradle.org/
  
  BUILD FAILED in 2m 3s
```

My buildscript generally uses JDK 17 or up. Is there a way to specify this when the action tries to run Gradle?

**Comment by mikepenz** [comment]
@ejektaflex this action does not specify the java version, and directly executes `gradlew` or `gradle` commands for you, but requires a working dev environment. 

The action will not install java on the chosen runner. You can use the `actions/setup-java` action for this purpose: https://github.com/actions/setup-java
