### ISSUE TITLE
Need Dependabot report in Sarif or CSV

### ISSUE THREAD

**Issue by ashutosh7107** [mikepenz/gradle-dependency-submission#348]
Hi,
I am able to get all the vulnerabilities of my android(gradle) project and I can see the vulnerabilities under security tab inside dependabot tab. Now I am looking to extract the vulnerabilities generated by dependabot. Looking a way to do that but not succeeded yet. Please guide me how to upload the dependabot vulnerabilities as an artifact as a sarif or CSV file.

**Comment by mikepenz** [comment]
@ashutosh7107 this action only focuses on retrieving the dependencies and uploading them via GitHubs API to show up in the dependency graph. 

Unfortunately I do not have information on how to upload the vulnerabilities as artifact or sarif file.

**Comment by ashutosh7107** [comment]
> @ashutosh7107 this action only focuses on retrieving the dependencies and uploading them via GitHubs API to show up in the dependency graph.
> 
> Unfortunately I do not have information on how to upload the vulnerabilities as artifact or sarif file.
> 
> If you have a link to GitHub API doc which does that with the dependency graph, I may have a look, but I believe this is out of scope for this action


Thanks for the response. One more thing I wanted to ask do you know at which path these dependabot vulnerabilities getting generated?(**example- /home/runner/work/${{ github.event.repository.name }}**/..... so that I can get the result directly from there.
<img width="1175" alt="Screenshot 2023-08-30 at 10 46 04 AM" src="https://github.com/mikepenz/gradle-dependency-submission/assets/56146357/8eda9569-6134-4864-b73f-945adf151ae8">
 )

**Comment by mikepenz** [comment]
This action does not generate a vulnerability report. This action only submits the dependency graph. 

The UI you show above is created by GitHub.

**Comment by ashutosh7107** [comment]
> This action does not generate a vulnerability report. This action only submits the dependency graph.
> 
> The UI you show above is created by GitHub.

Oh Ok. Any idea where this is getting created by GitHub? It should be on some path right?

**Comment by mikepenz** [comment]
No, this is produced by GitHub systems internally. 

Please refer to GitHubs documentation. This is unrelated to this action.
