### ISSUE TITLE
Using with Github Dependency Review

### ISSUE THREAD

**Issue by mandrachek** [mikepenz/gradle-dependency-submission#460]
I'm looking at using this plugin in conjunction with the dependency review plugin.

With regards to the note in the ReadMe:

"Currently the action has to be run on the default branch. Running it as part of a PR won't update the [Dependency graph](https://github.com/mikepenz/gradle-dependency-submission/network/dependencies) of your projects [Insights](https://github.com/mikepenz/gradle-dependency-submission/pulse) - This seems to be a GitHub requirement."

According to the [best practices](https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-dependency-review#using-github-actions-to-access-the-dependency-submission-api-and-the-dependency-review-api)  for using the dependency review API and the dependency submission API, when combining the dependency submission API, and the dependency review API, they should be run in the same action.

Given the documentation states: "The dependency review API and the dependency review action both work by comparing dependency changes in a pull request with the state of your dependencies in the head commit of your target branch."

It would appear that I should run this agains the default branch after every merge, as well as on every PR along with the dependency review, something like so:

- Open PR against default branch
   - run gradle-dependency-submission on the branch
   - run dependency review on the branch

- After PR merge to default branch
   - run gradle-dependency-submission again
   
Would that make sense?

**Comment by mikepenz** [comment]
Good day. 

Unfortunately, I don't have experience with the dependency-review action. It can very likely be that it is possible via the dependency-review action to also compare the dependency submission from a PR. 

It is worth noting the warning in the README only relates to the dependencies showing up in the `Insights` (there were reports where people would do it on a PR, and then the insights won't show it). There is no technical limitation of this action itself doing it from a different branch, and you can definitely run it from a PR which is on a different PR. (I don't know if the dependency-review will pick things up) 

Your outlined workflow setup sounds good, and seems to make sense.

**Comment by mikepenz** [comment]
Thank for again for the report. 

With the official `Gradle Build Action` having now official support for the dependency graph, I'd advice to move to this dependency instead: https://github.com/gradle/gradle-build-action?tab=readme-ov-file#github-dependency-graph-support
