### ISSUE TITLE
What's the default for `use-gradlew`?

### ISSUE THREAD

**Issue by nigelcharman** [mikepenz/gradle-dependency-submission#70]
Please add the default value for `use-gradlew` to the README. The other inputs show the defaults.

_(My guess is it's `false` from browsing the code since I can't see it explicitly set)_

**Comment by mikepenz** [comment]
GitHub actions set their defaults in the `action.yml` file: https://github.com/mikepenz/gradle-dependency-submission/blob/main/action.yml#L15

For this config the default `true`. 

Maybe you'd like to open a PR to add this note in the README?

**Comment by mikepenz** [comment]
Thank you very much
