### ISSUE TITLE
Multi-project dependencies

### ISSUE THREAD

**Issue by agonzalez-plume** [mikepenz/gradle-dependency-submission#72]
Love this project, I am awaiting github to support gradle dependencies. Maybe they will use the gradle.lockfile and leave generating the deps to the build.gradle in the project and using that file to import into dependabot. In the meantime, I am left with writing something myself using a SBOM from cdxgen or potentially a utility like this gradle-dependency-submission.

My project has sub projects in multiple github repos. I've got that covered by checking out with submodules: recursive and that works.
Dependencies listing for the project is complex. lots of variants,  multiple targets.

This action is pretty good, I was able to pick the path, the build.gradle, the target. All that worked and generated a dependency tree.

The dep tree though is too complicated and the parser can't handle it. I thought I would open an Issue to describe it, I can probably propose some changes, but didn't have the time to look anymore at this action source.

Here's how our deps start

```
+--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.6.21 -> 1.6.10
  |    +--- org.jetbrains.kotlin:kotlin-stdlib:1.6.10 -> 1.6.21
  |    |    +--- org.jetbrains.kotlin:kotlin-stdlib-common:1.6.21
  |    |    \--- org.jetbrains:annotations:13.0 -> 18.0.0
  |    \--- org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.6.10 -> 1.6.21
  |         \--- org.jetbrains.kotlin:kotlin-stdlib:1.6.21 (*)
  +--- project :myapp-ui
  |    +--- project :myapp-module-ui
  |    |    +--- project :widgets
  |    |    |    +--- com.google.android.material:material:1.5.0 (*)
  |    |    |    +--- androidx.constraintlayout:constraintlayout:2.0.0 -> 2.0.1 (*)
  |    |    +--- project :resources-deviceicons
  |    |    +--- project :strings-common
  |    |    |    \--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.6.21 -> 1.6.10 (*)
  |    |    +--- project :styles
  |    |    |    \--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.6.21 -> 1.6.10 (*)
```
Inside these projects are other dependencies that i've shortened and sometimes left out for brevity.

The parser tries to parse
Parsing gradle dependencies graph - ':myapp'
  Found a project dependency, skipping (Currently not supported) - +--- project :myapp-ui
  Error: Could not parse package: '|    +--- project :myapp-module-ui' (1)

**Comment by mikepenz** [comment]
@agonzalez-plume thank you for the report. 

For now we skip the `Found a project dependency, skipping (Currently not supported)` as it is not possible to have these being included in the hierarchy constructed for the dependency submission API (as those are not gradle packages).

There are a few open questions on how they would be handled:
- uploaded as their own report
- skip the `project` declaration and just include child dependencies as if they were declared directly with the main project
- other ways?

**Comment by mikepenz** [comment]
To add more context on this. What would be the parent of `com.google.android.material:material` for the following

```
+--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.6.21 -> 1.6.10
| +--- org.jetbrains.kotlin:kotlin-stdlib:1.6.10 -> 1.6.21
| | +--- org.jetbrains.kotlin:kotlin-stdlib-common:1.6.21
| | --- org.jetbrains:annotations:13.0 -> 18.0.0
| --- org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.6.10 -> 1.6.21
| --- org.jetbrains.kotlin:kotlin-stdlib:1.6.21 ()
+--- project :myapp-ui
| +--- project :myapp-module-ui
| | +--- project :widgets
| | | +--- com.google.android.material:material:1.5.0 ()
```

`widgets` can't be defined in the dependency submission API as it's not a valid package spec. 
So it would fallback to be a root dependency, even though this is not correct. 

As such it probably would be advised to have every `module`/`project` as its own import. 

While currently done manually: https://github.com/mikepenz/gradle-dependency-submission/blob/main/.github/workflows/gradle-dependency-submission.yml#L28-L42

Maybe it would be worth to explore auto discovery of modules 🤔

**Comment by agonzalez-plume** [comment]
I would skip the projects and just include them directly, that's what  happens when a SBOM is created (w/cdxgen) It's a comprehensive listing of packages.

As well when I used the new gradle feature to create a gradle.lockfile, this format lists out all the dependencies in a different format which is easier to parse. The below shows a dependency and then the targets they are associated with. I can cat this file and grep for a target and see deps for that build. I was going to create a script to send to github dependency api, though I'm not sure how well Github will use that dep to look for vulnerabiltiies since they vuln repos may not know about that dep.

```
com.google.android.gms:play-services-places-placereport:17.0.0=target1DebugRuntimeClasspath,target1DebugUnitTestRuntimeClasspath,target1ReleaseRuntimeClasspath,target1ReleaseUnitTestRuntimeClasspath
com.google.android.gms:play-services-stats:17.0.2=target1DebugAndroidTestCompileClasspath,target1DebugCompileClasspath,target1DebugRuntimeClasspath,target1DebugUnitTestCompileClasspath,target1DebugUnitTestRuntimeClasspath,target1ReleaseCompileClasspath,target1ReleaseRuntimeClasspath,target1ReleaseUnitTestCompileClasspath,target1ReleaseUnitTestRuntimeClasspath
com.google.android.gms:play-services-tasks:18.0.1=target1DebugAndroidTestCompileClasspath,target1DebugCompileClasspath,target1DebugRuntimeClasspath,target1DebugUnitTestCompileClasspath,target1DebugUnitTestRuntimeClasspath,target1ReleaseCompileClasspath,target1ReleaseRuntimeClasspath,target1ReleaseUnitTestCompileClasspath,target1ReleaseUnitTestRuntimeClasspath
com.google.android.material:material:1.5.0=target1DebugAndroidTestCompileClasspath,target1DebugAndroidTestRuntimeClasspath,target1DebugCompileClasspath,target1DebugRuntimeClasspath,target1DebugUnitTestCompileClasspath,target1DebugUnitTestRuntimeClasspath,target1ReleaseCompileClasspath,target1ReleaseRuntimeClasspath,target1ReleaseUnitTestCompileClasspath,target1ReleaseUnitTestRuntimeClasspath
com.google.android:annotations:4.1.1.4=target1DebugRuntimeClasspath,target1DebugUnitTestRuntimeClasspath,target1ReleaseRuntimeClasspath,target1ReleaseUnitTestRuntimeClasspath
com.google.code.findbugs:jsr305:3.0.2=_agp_internal_javaPreCompiletarget1DebugAndroidTest_kaptClasspath,_agp_internal_javaPreCompiletarget1DebugUnitTest_kaptClasspath,_agp_internal_javaPreCompiletarget1Debug_kaptClasspath,_agp_internal_javaPreCompiletarget1ReleaseUnitTest_kaptClasspath,_agp_internal_javaPreCompiletarget1Release_kaptClasspath,kapt,kaptAndroidTest,kaptAndroidTestDebug,kaptAndroidTesttarget1,kaptAndroidTesttarget1Debug,kaptAndroidTestRelease,kaptClasspath_kapttarget1DebugAndroidTestKotlin,kaptClasspath_kapttarget1DebugKotlin,kaptClasspath_kapttarget1ReleaseKotlin,kaptDebug,kapttarget1,kapttarget1Debug,kapttarget1Release,kaptRelease,kaptTest,kaptTestDebug,kaptTestFixtures,kaptTestFixturesDebug,kaptTestFixturestarget1,kaptTestFixturesRelease,kaptTesttarget1,kaptTesttarget1Debug,kaptTesttarget1Release,kaptTestRelease,lintChecks,target1DebugAndroidTestCompileClasspath,target1DebugAndroidTestRuntimeClasspath,target1DebugCompileClasspath,target1DebugRuntimeClasspath,target1DebugUnitTestCompileClasspath,target1DebugUnitTestRuntimeClasspath,target1ReleaseCompileClasspath,target1ReleaseRuntimeClasspath,target1ReleaseUnitTestCompileClasspath,target1ReleaseUnitTestRuntimeClasspath
com.google.code.gson:gson:2.8.6=lintChecks,target1DebugAndroidTestCompileClasspath
com.google.code.gson:gson:2.8.9=target1DebugCompileClasspath,target1DebugRuntimeClasspath,target1DebugUnitTestCompileClasspath,target1DebugUnitTestRuntimeClasspath,target1ReleaseCompileClasspath,target1ReleaseRuntimeClasspath,target1ReleaseUnitTestCompileClasspath,target1ReleaseUnitTestRuntimeClasspath
```

**Comment by agonzalez-plume** [comment]
Looking through the code, I am realizing your main result is a 'manifest' and then snapshot as wanted by github submission toolkit in the format of:

```
interface Result {
  packageCache: PackageCache
  directDependencies: PackageURL[]
  indirectDependencies: PackageURL[]
}
```
Hmm, SBOM doesn't preserve that in my repo and the gradle.lockfile I was generating wouldn't preserve that either.

So I get what you are asking. What does it mean to have it as a new submission in the github product? I"m not sure I can visualize what that looks like

**Comment by mikepenz** [comment]
@agonzalez-plume thank you for reporting back. 

Regarding doing the submission per project. 

I was thinking maybe like I do in this test right now whereas each module (each test project) has it's own section in the dependencies. Similar like every other thing getting its own section (https://github.com/mikepenz/gradle-dependency-submission/network/dependencies)

<img width="950" alt="Screenshot 2022-08-19 at 08 18 25" src="https://user-images.githubusercontent.com/1476232/185555511-e36d09b1-ce4a-4ba6-8cbd-814dcd2331fd.png">

<img width="944" alt="Screenshot 2022-08-19 at 08 18 34" src="https://user-images.githubusercontent.com/1476232/185555537-62ae506c-02ee-4f4c-b031-d2d00c2d96ee.png">

The question is only if I am able to properly detect the path to the root build file for each module without making too many assumptions

**Comment by mikepenz** [comment]
What's also interesting. For the maven ecosystem GitHub currently does not display the hierarchy even though the action would already upload it in such a way that it would be preserved. 

An example for the node dependency display:
<img width="886" alt="Screenshot 2022-08-19 at 08 21 12" src="https://user-images.githubusercontent.com/1476232/185555912-7f52088c-7fc9-4d8b-95e7-4b19a8ad67ae.png">
